version: '3.8'

services:
  # PHP-FPM Service (Custom build with mysqli)
  ujian_php:
    build: .
    container_name: ujian_php
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - ichdsf_default

  # Nginx Service
  ujian_nginx:
    image: nginx:alpine
    container_name: ujian_nginx
    restart: always
    ports:
      - "${APP_PORT}:80" # Mengambil port dari .env
    volumes:
      - .:/var/www/html
      - ./nginx/ujian.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ujian_php
    networks:
      - ichdsf_default

networks:
  ichdsf_default:
    external: true
