version: '3.8'

services:
  info_ujian_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: info_ujian_node
    restart: always
    ports:
      - "8085:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=36aed57f410a_global_mariadb
      - DB_USER=root
      - DB_PASSWORD=IchdsfDB2026!
      - DB_NAME=stb_ujian_db
      - PORT=3000
    networks:
      - ichdsf_default

networks:
  ichdsf_default:
    external: true
